//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetlistManager.Resources.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Storage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Storage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetlistManager.Resources.Storage.Storage", typeof(Storage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please click the button below to reset your password:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&apos;{0}&apos; style=&apos;
        ///    display:inline-block;
        ///    padding:10px 20px;
        ///    background-color:#4CAF50;
        ///    color:white;
        ///    text-decoration:none;
        ///    border-radius:5px;&apos;&gt;
        ///    Reset Password
        ///&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If you cannot click the button, copy and paste this link into your browser:&lt;/p&gt;
        ///&lt;p&gt;{0}&lt;/p&gt;.
        /// </summary>
        public static string ResetPasswordMail {
            get {
                return ResourceManager.GetString("ResetPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your Setlist Manager password.
        /// </summary>
        public static string ResetPasswordMailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please click the button below to verify your account:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&apos;{0}&apos; style=&apos;
        ///    display:inline-block;
        ///    padding:10px 20px;
        ///    background-color:#4CAF50;
        ///    color:white;
        ///    text-decoration:none;
        ///    border-radius:5px;&apos;&gt;
        ///    Verify Email
        ///&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If you cannot click the button, copy and paste this link into your browser:&lt;/p&gt;
        ///&lt;p&gt;{0}&lt;/p&gt;.
        /// </summary>
        public static string VerifyEmailMail {
            get {
                return ResourceManager.GetString("VerifyEmailMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your Setlist Manager account.
        /// </summary>
        public static string VerifyEmailMailSubject {
            get {
                return ResourceManager.GetString("VerifyEmailMailSubject", resourceCulture);
            }
        }
    }
}
