// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SetlistManager.API.Data;

#nullable disable

namespace SetlistManager.API.Migrations;

[DbContext(typeof(APIDbContext))]
[Migration("20250708112751_help2")]
partial class help2
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("InstrumentUser", b =>
            {
                b.Property<int>("InstrumentsId")
                    .HasColumnType("int");

                b.Property<int>("UsersId")
                    .HasColumnType("int");

                b.HasKey("InstrumentsId", "UsersId");

                b.HasIndex("UsersId");

                b.ToTable("InstrumentUser");
            });

        modelBuilder.Entity("RoomSetlist", b =>
            {
                b.Property<int>("RoomsId")
                    .HasColumnType("int");

                b.Property<int>("SetlistsId")
                    .HasColumnType("int");

                b.HasKey("RoomsId", "SetlistsId");

                b.HasIndex("SetlistsId");

                b.ToTable("RoomSetlist");
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.Instrument", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Instruments");
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.Language", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Languages");
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.Room", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("HostId")
                    .HasColumnType("int");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("IsPublic")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("UpdatedBy")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Rooms");
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.Setlist", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("CreatorId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("UpdatedBy")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CreatorId");

                b.ToTable("Setlists");
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.Song", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Artist")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("AudioURL")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("BPM")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("LanguageId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TabsURL")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Tuning")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("UpdatedBy")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("LanguageId");

                b.ToTable("Songs");
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<int>("RoomId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("RoomId");

                b.ToTable("Users");
            });

        modelBuilder.Entity("SetlistSong", b =>
            {
                b.Property<int>("SetlistsId")
                    .HasColumnType("int");

                b.Property<int>("SongsId")
                    .HasColumnType("int");

                b.HasKey("SetlistsId", "SongsId");

                b.HasIndex("SongsId");

                b.ToTable("SetlistSong");
            });

        modelBuilder.Entity("InstrumentUser", b =>
            {
                b.HasOne("SetlistManager.API.Data.Entities.Instrument", null)
                    .WithMany()
                    .HasForeignKey("InstrumentsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SetlistManager.API.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UsersId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("RoomSetlist", b =>
            {
                b.HasOne("SetlistManager.API.Data.Entities.Room", null)
                    .WithMany()
                    .HasForeignKey("RoomsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SetlistManager.API.Data.Entities.Setlist", null)
                    .WithMany()
                    .HasForeignKey("SetlistsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.Setlist", b =>
            {
                b.HasOne("SetlistManager.API.Data.Entities.User", "Creator")
                    .WithMany()
                    .HasForeignKey("CreatorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Creator");
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.Song", b =>
            {
                b.HasOne("SetlistManager.API.Data.Entities.Language", "Language")
                    .WithMany()
                    .HasForeignKey("LanguageId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Language");
            });

        modelBuilder.Entity("SetlistManager.API.Data.Entities.User", b =>
            {
                b.HasOne("SetlistManager.API.Data.Entities.Room", "Room")
                    .WithMany()
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Room");
            });

        modelBuilder.Entity("SetlistSong", b =>
            {
                b.HasOne("SetlistManager.API.Data.Entities.Setlist", null)
                    .WithMany()
                    .HasForeignKey("SetlistsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SetlistManager.API.Data.Entities.Song", null)
                    .WithMany()
                    .HasForeignKey("SongsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
